language: java
sudo: false
install: true

dist: trusty
jdk:
- oraclejdk8

os:
- linux

branches:
  only:
   - development
   - dev/ci

before_cache:
- rm -f $HOME/DogsStartUp/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/DogsStartUp/.gradle/caches/*/plugin-resolution

cache:
  directories:
  - $HOME/DogsStartUp/.gradle/caches/
  - $HOME/DogsStartUp/.gradle/wrapper/

script:
- ./gradlew assemble
- ./gradlew clean build sonarqube -s
- ./gradlew update
